---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer
  namespace: morse-code
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: morse-code
  name: deployer
rules:
- apiGroups: ["", "extensions", "apps", "networking.k8s.io"]
  resources: ["deployments", "replicasets", "pods", "services", "ingresses", ""]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer
  namespace: morse-code
subjects:
- kind: ServiceAccount
  name: deployer
  apiGroup: ""
roleRef:
  kind: Role
  name: deployer
  apiGroup: "rbac.authorization.k8s.io"